// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/watch/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=pkg/watch/interfaces.go -destination=pkg/watch/mocks/interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	watch "golang.nuinfra.api-server/pkg/watch"
	proto "google.golang.org/protobuf/proto"
)

// MockWatchableStream is a mock of WatchableStream interface.
type MockWatchableStream[E proto.Message] struct {
	ctrl     *gomock.Controller
	recorder *MockWatchableStreamMockRecorder[E]
	isgomock struct{}
}

// MockWatchableStreamMockRecorder is the mock recorder for MockWatchableStream.
type MockWatchableStreamMockRecorder[E proto.Message] struct {
	mock *MockWatchableStream[E]
}

// NewMockWatchableStream creates a new mock instance.
func NewMockWatchableStream[E proto.Message](ctrl *gomock.Controller) *MockWatchableStream[E] {
	mock := &MockWatchableStream[E]{ctrl: ctrl}
	mock.recorder = &MockWatchableStreamMockRecorder[E]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchableStream[E]) EXPECT() *MockWatchableStreamMockRecorder[E] {
	return m.recorder
}

// GetWatchersCount mocks base method.
func (m *MockWatchableStream[E]) GetWatchersCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchersCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetWatchersCount indicates an expected call of GetWatchersCount.
func (mr *MockWatchableStreamMockRecorder[E]) GetWatchersCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchersCount", reflect.TypeOf((*MockWatchableStream[E])(nil).GetWatchersCount))
}

// Publish mocks base method.
func (m *MockWatchableStream[E]) Publish(ctx context.Context, event E) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockWatchableStreamMockRecorder[E]) Publish(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockWatchableStream[E])(nil).Publish), ctx, event)
}

// StopWatching mocks base method.
func (m *MockWatchableStream[E]) StopWatching(ctx context.Context, watcherID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopWatching", ctx, watcherID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopWatching indicates an expected call of StopWatching.
func (mr *MockWatchableStreamMockRecorder[E]) StopWatching(ctx, watcherID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopWatching", reflect.TypeOf((*MockWatchableStream[E])(nil).StopWatching), ctx, watcherID)
}

// Watch mocks base method.
func (m *MockWatchableStream[E]) Watch(ctx context.Context, watcher *watch.Watcher[E]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, watcher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockWatchableStreamMockRecorder[E]) Watch(ctx, watcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWatchableStream[E])(nil).Watch), ctx, watcher)
}
