// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cli/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=pkg/cli/interfaces.go -destination=pkg/cli/mocks/interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cli "github.com/alan-ghelardi/yaghan/ctl/pkg/cli"
	gomock "go.uber.org/mock/gomock"
)

// MockPrompter is a mock of Prompter interface.
type MockPrompter struct {
	ctrl     *gomock.Controller
	recorder *MockPrompterMockRecorder
	isgomock struct{}
}

// MockPrompterMockRecorder is the mock recorder for MockPrompter.
type MockPrompterMockRecorder struct {
	mock *MockPrompter
}

// NewMockPrompter creates a new mock instance.
func NewMockPrompter(ctrl *gomock.Controller) *MockPrompter {
	mock := &MockPrompter{ctrl: ctrl}
	mock.recorder = &MockPrompterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompter) EXPECT() *MockPrompterMockRecorder {
	return m.recorder
}

// ClearBelow mocks base method.
func (m *MockPrompter) ClearBelow(position cli.Position) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearBelow", position)
}

// ClearBelow indicates an expected call of ClearBelow.
func (mr *MockPrompterMockRecorder) ClearBelow(position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearBelow", reflect.TypeOf((*MockPrompter)(nil).ClearBelow), position)
}

// Confirmation mocks base method.
func (m *MockPrompter) Confirmation(message string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirmation", message)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirmation indicates an expected call of Confirmation.
func (mr *MockPrompterMockRecorder) Confirmation(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirmation", reflect.TypeOf((*MockPrompter)(nil).Confirmation), message)
}

// Cursor mocks base method.
func (m *MockPrompter) Cursor() cli.Cursor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor")
	ret0, _ := ret[0].(cli.Cursor)
	return ret0
}

// Cursor indicates an expected call of Cursor.
func (mr *MockPrompterMockRecorder) Cursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockPrompter)(nil).Cursor))
}

// KeyInput mocks base method.
func (m *MockPrompter) KeyInput(label string, acceptedKeys []rune) (rune, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyInput", label, acceptedKeys)
	ret0, _ := ret[0].(rune)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeyInput indicates an expected call of KeyInput.
func (mr *MockPrompterMockRecorder) KeyInput(label, acceptedKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyInput", reflect.TypeOf((*MockPrompter)(nil).KeyInput), label, acceptedKeys)
}

// Select mocks base method.
func (m *MockPrompter) Select(label string, items []cli.ListItem) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", label, items)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockPrompterMockRecorder) Select(label, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockPrompter)(nil).Select), label, items)
}

// TextInput mocks base method.
func (m *MockPrompter) TextInput(label string, opts cli.TextInputOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TextInput", label, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TextInput indicates an expected call of TextInput.
func (mr *MockPrompterMockRecorder) TextInput(label, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextInput", reflect.TypeOf((*MockPrompter)(nil).TextInput), label, opts)
}

// MockCursor is a mock of Cursor interface.
type MockCursor struct {
	ctrl     *gomock.Controller
	recorder *MockCursorMockRecorder
	isgomock struct{}
}

// MockCursorMockRecorder is the mock recorder for MockCursor.
type MockCursorMockRecorder struct {
	mock *MockCursor
}

// NewMockCursor creates a new mock instance.
func NewMockCursor(ctrl *gomock.Controller) *MockCursor {
	mock := &MockCursor{ctrl: ctrl}
	mock.recorder = &MockCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCursor) EXPECT() *MockCursorMockRecorder {
	return m.recorder
}

// Move mocks base method.
func (m *MockCursor) Move(position cli.Position) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Move", position)
}

// Move indicates an expected call of Move.
func (mr *MockCursorMockRecorder) Move(position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockCursor)(nil).Move), position)
}

// Position mocks base method.
func (m *MockCursor) Position() (cli.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Position")
	ret0, _ := ret[0].(cli.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Position indicates an expected call of Position.
func (mr *MockCursorMockRecorder) Position() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Position", reflect.TypeOf((*MockCursor)(nil).Position))
}

// MockListItem is a mock of ListItem interface.
type MockListItem struct {
	ctrl     *gomock.Controller
	recorder *MockListItemMockRecorder
	isgomock struct{}
}

// MockListItemMockRecorder is the mock recorder for MockListItem.
type MockListItemMockRecorder struct {
	mock *MockListItem
}

// NewMockListItem creates a new mock instance.
func NewMockListItem(ctrl *gomock.Controller) *MockListItem {
	mock := &MockListItem{ctrl: ctrl}
	mock.recorder = &MockListItemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListItem) EXPECT() *MockListItemMockRecorder {
	return m.recorder
}

// Text mocks base method.
func (m *MockListItem) Text() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Text")
	ret0, _ := ret[0].(string)
	return ret0
}

// Text indicates an expected call of Text.
func (mr *MockListItemMockRecorder) Text() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Text", reflect.TypeOf((*MockListItem)(nil).Text))
}

// Value mocks base method.
func (m *MockListItem) Value() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(any)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockListItemMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockListItem)(nil).Value))
}
