// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/network/driver.go
//
// Generated by this command:
//
//	mockgen -source=pkg/network/driver.go -destination=pkg/network/mocks/driver.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	network "github.com/alan-ghelardi/yaghan/daemon/pkg/network"
	gomock "go.uber.org/mock/gomock"
)

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
	isgomock struct{}
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// Deprovision mocks base method.
func (m *MockDriver) Deprovision(index int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deprovision", index)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deprovision indicates an expected call of Deprovision.
func (mr *MockDriverMockRecorder) Deprovision(index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deprovision", reflect.TypeOf((*MockDriver)(nil).Deprovision), index)
}

// Provision mocks base method.
func (m *MockDriver) Provision(index int, egress *network.EgressPolicy) (network.NamespaceHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provision", index, egress)
	ret0, _ := ret[0].(network.NamespaceHandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Provision indicates an expected call of Provision.
func (mr *MockDriverMockRecorder) Provision(index, egress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provision", reflect.TypeOf((*MockDriver)(nil).Provision), index, egress)
}
