package service_test

import (
	"context"
	"errors"
	"io"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	cpv1 "golang.nuinfra.net/apis/gen/nuinfra/control_plane/v1alpha1"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

const (
	testNodeID    = "node-A"
	otherNodeID   = "node-B"
	receiveBudget = 10 * time.Second
)

// connectAs opens an EstablishSession stream for nodeID and waits for the
// ConnectionResponse acknowledgement. sessionID == 0 lets the server
// auto-generate; > 0 attempts to resume.
func connectAs(ctx context.Context, t *testing.T, h *harness, nodeID string, sessionID int64) (cpv1.ClusterService_EstablishSessionClient, int64) { //nolint:unparam // nodeID is intentionally a parameter for future per-node test cases
	t.Helper()
	stream, err := h.cluster.EstablishSession(ctx)
	require.NoError(t, err)

	require.NoError(t, stream.Send(&cpv1.EstablishSessionRequest{
		Operation: &cpv1.EstablishSessionRequest_Connect{
			Connect: &cpv1.ConnectionRequest{
				SessionId: sessionID,
				Node: &cpv1.Node{
					Metadata: &cpv1.NodeMeta{Id: nodeID},
					Resources: &cpv1.NodeResources{
						VcpuCount: 4,
						MemoryMib: 8192,
					},
				},
			},
		},
	}))

	resp, err := stream.Recv()
	require.NoError(t, err, "expected ConnectionResponse acknowledgement")
	ack := resp.GetAcknowledge()
	require.NotNil(t, ack, "first response must be an acknowledgement, got %T", resp.GetMessage())
	require.Positive(t, ack.GetSessionId())
	return stream, ack.GetSessionId()
}

// recvEvent reads the next response and asserts it carries an Event. Fails
// the test if anything else arrives or the read times out.
func recvEvent(t *testing.T, stream cpv1.ClusterService_EstablishSessionClient) *cpv1.Event {
	t.Helper()
	type recvResult struct {
		resp *cpv1.EstablishSessionResponse
		err  error
	}
	ch := make(chan recvResult, 1)
	go func() {
		resp, err := stream.Recv()
		ch <- recvResult{resp, err}
	}()
	select {
	case r := <-ch:
		require.NoError(t, r.err)
		ev := r.resp.GetEvent()
		require.NotNil(t, ev, "expected Event, got %T", r.resp.GetMessage())
		return ev
	case <-time.After(receiveBudget):
		t.Fatal("timed out waiting for Event")
		return nil
	}
}

// recvError reads the next response and asserts it carries an in-band Error.
func recvError(t *testing.T, stream cpv1.ClusterService_EstablishSessionClient) *cpv1.EstablishSessionResponse {
	t.Helper()
	resp, err := stream.Recv()
	require.NoError(t, err)
	require.NotNil(t, resp.GetError(), "expected in-band Error, got %T", resp.GetMessage())
	return resp
}

// publishSandboxAssignedTo creates a sandbox via SandboxService and then
// stamps it with NodeRef.Id == nodeID via the test-side WatchableDB to
// simulate the future scheduler. The resulting Event flows through redis to
// any registered watcher whose filter matches.
func publishSandboxAssignedTo(ctx context.Context, t *testing.T, h *harness, sandboxID, nodeID string) *cpv1.Sandbox {
	t.Helper()

	createResp, err := h.client.CreateSandbox(ctx, newCreateRequest(withID(sandboxID)))
	require.NoError(t, err)
	sb := createResp.GetSandbox()

	sb.Node = &cpv1.NodeRef{Id: nodeID}
	require.NoError(t, h.db.Update(ctx, sb))
	return sb
}

func TestEstablishSession_AcknowledgesWithAutoGeneratedSessionID(t *testing.T) {
	h := startService(t, withEventStream())
	ctx := t.Context()

	stream, sessionID := connectAs(ctx, t, h, testNodeID, 0)
	defer func() { _ = stream.CloseSend() }()

	assert.Positive(t, sessionID, "server must auto-generate a session id")
}

func TestEstablishSession_DeliversEventsForAssignedNode(t *testing.T) {
	h := startService(t, withEventStream())
	ctx := t.Context()

	stream, _ := connectAs(ctx, t, h, testNodeID, 0)
	defer func() { _ = stream.CloseSend() }()

	sb := publishSandboxAssignedTo(ctx, t, h, "sb-deliver", testNodeID)

	got := recvEvent(t, stream)
	require.NotNil(t, got.GetSandbox())
	assert.Equal(t, sb.GetMetadata().GetId(), got.GetSandbox().GetMetadata().GetId())
	assert.Equal(t, testNodeID, got.GetSandbox().GetNode().GetId())
}

func TestEstablishSession_FilterDropsEventsForOtherNodes(t *testing.T) {
	h := startService(t, withEventStream())
	ctx := t.Context()

	stream, _ := connectAs(ctx, t, h, testNodeID, 0)
	defer func() { _ = stream.CloseSend() }()

	// Publish an event for a different node first; it must NOT be delivered.
	publishSandboxAssignedTo(ctx, t, h, "sb-other", otherNodeID)

	// Then publish for our node; this one must arrive.
	mine := publishSandboxAssignedTo(ctx, t, h, "sb-mine", testNodeID)

	got := recvEvent(t, stream)
	assert.Equal(t, mine.GetMetadata().GetId(), got.GetSandbox().GetMetadata().GetId(),
		"watcher must drop events for nodes other than its own")
}

func TestEstablishSession_ResumeReplacesPriorSession(t *testing.T) {
	h := startService(t, withEventStream())
	ctx := t.Context()

	first, sessionID := connectAs(ctx, t, h, testNodeID, 0)

	// Reconnect under the same session id.
	second, _ := connectAs(ctx, t, h, testNodeID, sessionID)
	defer func() { _ = second.CloseSend() }()

	// The first stream is now stale; its next Recv should return EOF or a
	// gRPC error indicating the watcher was closed.
	_, err := first.Recv()
	require.Error(t, err, "prior session's Recv must surface the takeover")
	if !errors.Is(err, io.EOF) {
		// Some grpc transports return Canceled / Unavailable rather than
		// the protocol-level EOF; either is acceptable for our purposes.
		st, ok := status.FromError(err)
		require.True(t, ok)
		assert.Contains(t, []codes.Code{codes.Canceled, codes.Unavailable, codes.Unknown, codes.Internal}, st.Code(),
			"unexpected status on takeover: %v", st.Code())
	}

	// New stream must still receive events.
	publishSandboxAssignedTo(ctx, t, h, "sb-after-resume", testNodeID)
	got := recvEvent(t, second)
	assert.Equal(t, "sb-after-resume", got.GetSandbox().GetMetadata().GetId())
}

func TestEstablishSession_UpdateSandboxHappyPath(t *testing.T) {
	h := startService(t, withEventStream())
	ctx := t.Context()

	stream, _ := connectAs(ctx, t, h, testNodeID, 0)
	defer func() { _ = stream.CloseSend() }()

	createResp, err := h.client.CreateSandbox(ctx, newCreateRequest(withID("sb-update-ok")))
	require.NoError(t, err)
	sb := createResp.GetSandbox()
	sb.Node = &cpv1.NodeRef{Id: testNodeID}

	require.NoError(t, stream.Send(&cpv1.EstablishSessionRequest{
		Operation: &cpv1.EstablishSessionRequest_UpdateSandbox{
			UpdateSandbox: &cpv1.UpdateSandboxRequest{Sandbox: sb},
		},
	}))

	// The successful update emits an Event back over the same stream.
	got := recvEvent(t, stream)
	updated := got.GetSandbox()
	assert.Equal(t, "sb-update-ok", updated.GetMetadata().GetId())
	assert.Equal(t, testNodeID, updated.GetNode().GetId())
	assert.True(t, proto.Equal(sb.GetIntent(), updated.GetIntent()))
}

func TestEstablishSession_UpdateSandboxVersionConflictReturnsInBandError(t *testing.T) {
	h := startService(t, withEventStream())
	ctx := t.Context()

	stream, _ := connectAs(ctx, t, h, testNodeID, 0)
	defer func() { _ = stream.CloseSend() }()

	createResp, err := h.client.CreateSandbox(ctx, newCreateRequest(withID("sb-update-conflict")))
	require.NoError(t, err)
	sb := createResp.GetSandbox()
	sb.Metadata.Version = 999 // stale; the DB will refuse the write
	sb.Node = &cpv1.NodeRef{Id: testNodeID}

	require.NoError(t, stream.Send(&cpv1.EstablishSessionRequest{
		Operation: &cpv1.EstablishSessionRequest_UpdateSandbox{
			UpdateSandbox: &cpv1.UpdateSandboxRequest{Sandbox: sb},
		},
	}))

	resp := recvError(t, stream)
	assert.Equal(t, int32(codes.Aborted), resp.GetError().GetCode())

	// The stream must remain open after a per-message error so the daemon
	// can retry. Sending a noop ping by closing send and reading EOF is
	// enough to confirm the server hasn't terminated.
	require.NoError(t, stream.CloseSend())
	for {
		_, err := stream.Recv()
		if err != nil {
			require.True(t, errors.Is(err, io.EOF) || isCancelled(err),
				"stream should close cleanly after CloseSend, got %v", err)
			return
		}
	}
}

func TestEstablishSession_FirstMessageMustBeConnect(t *testing.T) {
	h := startService(t, withEventStream())
	ctx := t.Context()

	stream, err := h.cluster.EstablishSession(ctx)
	require.NoError(t, err)

	// Send an UpdateSandboxRequest as the first message — protocol violation.
	require.NoError(t, stream.Send(&cpv1.EstablishSessionRequest{
		Operation: &cpv1.EstablishSessionRequest_UpdateSandbox{
			UpdateSandbox: &cpv1.UpdateSandboxRequest{Sandbox: &cpv1.Sandbox{
				Metadata: &cpv1.SandboxMeta{Id: "x", Namespace: validNamespace},
				Resources: &cpv1.Resources{
					VcpuCount: 1,
					MemoryMib: 128,
				},
			}},
		},
	}))

	_, err = stream.Recv()
	require.Error(t, err)
	st, ok := status.FromError(err)
	require.True(t, ok, "error is not a gRPC status: %v", err)
	assert.Equal(t, codes.InvalidArgument, st.Code())
}

func isCancelled(err error) bool {
	if errors.Is(err, context.Canceled) {
		return true
	}
	st, ok := status.FromError(err)
	return ok && (st.Code() == codes.Canceled || st.Code() == codes.Unavailable)
}
