// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/node/reporter.go
//
// Generated by this command:
//
//	mockgen -source=pkg/node/reporter.go -destination=pkg/node/mocks/reporter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	control_planev1alpha1 "golang.nuinfra.net/apis/gen/nuinfra/control_plane/v1alpha1"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// ReportNodeMetrics mocks base method.
func (m *MockReporter) ReportNodeMetrics(ctx context.Context, nodeMetrics *control_planev1alpha1.NodeMetrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportNodeMetrics", ctx, nodeMetrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportNodeMetrics indicates an expected call of ReportNodeMetrics.
func (mr *MockReporterMockRecorder) ReportNodeMetrics(ctx, nodeMetrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportNodeMetrics", reflect.TypeOf((*MockReporter)(nil).ReportNodeMetrics), ctx, nodeMetrics)
}

// ReportStatusPhase mocks base method.
func (m *MockReporter) ReportStatusPhase(ctx context.Context, phase control_planev1alpha1.NodeStatus_Phase, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportStatusPhase", ctx, phase, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportStatusPhase indicates an expected call of ReportStatusPhase.
func (mr *MockReporterMockRecorder) ReportStatusPhase(ctx, phase, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportStatusPhase", reflect.TypeOf((*MockReporter)(nil).ReportStatusPhase), ctx, phase, message)
}
