syntax = "proto3";

package nuinfra.data_plane.v1alpha1;

import "google/rpc/status.proto";
import "nuinfra/data_plane/v1alpha1/daemon.proto";

message AgentRequest {
  uint64 id = 1;

  oneof payload {
    ExecRequest exec_request = 2;
    CancelRequest cancel = 3;
    StdinChunk stdin = 4;
    ResizePTY resize = 5;
    UploadFileRequest upload_file = 6;
    DownloadFileRequest download_file = 7;
  }
}

message AgentResponse {
  uint64 id = 1;

  oneof payload {
    google.rpc.Status error = 2;
    ExecResponse exec_response = 3;
    UploadFileResponse upload_file = 5;
    DownloadFileResponse download_file = 6;
  }
}
