// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/snapshot/types.go
//
// Generated by this command:
//
//	mockgen -source=pkg/snapshot/types.go -destination=pkg/snapshot/mocks/types.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	snapshot "github.com/alan-ghelardi/yaghan/daemon/pkg/snapshot"
	gomock "go.uber.org/mock/gomock"
)

// MockDurableStore is a mock of DurableStore interface.
type MockDurableStore struct {
	ctrl     *gomock.Controller
	recorder *MockDurableStoreMockRecorder
	isgomock struct{}
}

// MockDurableStoreMockRecorder is the mock recorder for MockDurableStore.
type MockDurableStoreMockRecorder struct {
	mock *MockDurableStore
}

// NewMockDurableStore creates a new mock instance.
func NewMockDurableStore(ctrl *gomock.Controller) *MockDurableStore {
	mock := &MockDurableStore{ctrl: ctrl}
	mock.recorder = &MockDurableStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDurableStore) EXPECT() *MockDurableStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDurableStore) Get(ctx context.Context, snapshotID string, contents *snapshot.ContentsWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, snapshotID, contents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockDurableStoreMockRecorder) Get(ctx, snapshotID, contents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDurableStore)(nil).Get), ctx, snapshotID, contents)
}

// Put mocks base method.
func (m *MockDurableStore) Put(ctx context.Context, snapshotID string, contents *snapshot.ContentsReader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, snapshotID, contents)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockDurableStoreMockRecorder) Put(ctx, snapshotID, contents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockDurableStore)(nil).Put), ctx, snapshotID, contents)
}
