// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/firecracker/types.go
//
// Generated by this command:
//
//	mockgen -source=pkg/firecracker/types.go -destination=pkg/firecracker/mocks/types.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	transport "golang.nuinfra.net/agent/transport"
	firecracker "golang.nuinfra.net/daemon/pkg/firecracker"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CreateMicroVM mocks base method.
func (m *MockProvider) CreateMicroVM(ctx context.Context, input *firecracker.CreateMicroVMInput) (firecracker.MicroVM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMicroVM", ctx, input)
	ret0, _ := ret[0].(firecracker.MicroVM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMicroVM indicates an expected call of CreateMicroVM.
func (mr *MockProviderMockRecorder) CreateMicroVM(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMicroVM", reflect.TypeOf((*MockProvider)(nil).CreateMicroVM), ctx, input)
}

// DeleteMicroVM mocks base method.
func (m *MockProvider) DeleteMicroVM(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMicroVM", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMicroVM indicates an expected call of DeleteMicroVM.
func (mr *MockProviderMockRecorder) DeleteMicroVM(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMicroVM", reflect.TypeOf((*MockProvider)(nil).DeleteMicroVM), ctx, id)
}

// GetMicroVM mocks base method.
func (m *MockProvider) GetMicroVM(id string) firecracker.MicroVM {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMicroVM", id)
	ret0, _ := ret[0].(firecracker.MicroVM)
	return ret0
}

// GetMicroVM indicates an expected call of GetMicroVM.
func (mr *MockProviderMockRecorder) GetMicroVM(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMicroVM", reflect.TypeOf((*MockProvider)(nil).GetMicroVM), id)
}

// Len mocks base method.
func (m *MockProvider) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockProviderMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockProvider)(nil).Len))
}

// Recover mocks base method.
func (m *MockProvider) Recover(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recover", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Recover indicates an expected call of Recover.
func (mr *MockProviderMockRecorder) Recover(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recover", reflect.TypeOf((*MockProvider)(nil).Recover), ctx)
}

// MockMicroVM is a mock of MicroVM interface.
type MockMicroVM struct {
	ctrl     *gomock.Controller
	recorder *MockMicroVMMockRecorder
	isgomock struct{}
}

// MockMicroVMMockRecorder is the mock recorder for MockMicroVM.
type MockMicroVMMockRecorder struct {
	mock *MockMicroVM
}

// NewMockMicroVM creates a new mock instance.
func NewMockMicroVM(ctrl *gomock.Controller) *MockMicroVM {
	mock := &MockMicroVM{ctrl: ctrl}
	mock.recorder = &MockMicroVMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMicroVM) EXPECT() *MockMicroVMMockRecorder {
	return m.recorder
}

// CreateSnapshot mocks base method.
func (m *MockMicroVM) CreateSnapshot(ctx context.Context) (*firecracker.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", ctx)
	ret0, _ := ret[0].(*firecracker.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockMicroVMMockRecorder) CreateSnapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockMicroVM)(nil).CreateSnapshot), ctx)
}

// Describe mocks base method.
func (m *MockMicroVM) Describe(ctx context.Context) (*firecracker.MicroVMInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Describe", ctx)
	ret0, _ := ret[0].(*firecracker.MicroVMInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Describe indicates an expected call of Describe.
func (mr *MockMicroVMMockRecorder) Describe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockMicroVM)(nil).Describe), ctx)
}

// NetworkIndex mocks base method.
func (m *MockMicroVM) NetworkIndex() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkIndex")
	ret0, _ := ret[0].(int)
	return ret0
}

// NetworkIndex indicates an expected call of NetworkIndex.
func (mr *MockMicroVMMockRecorder) NetworkIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkIndex", reflect.TypeOf((*MockMicroVM)(nil).NetworkIndex))
}

// Pause mocks base method.
func (m *MockMicroVM) Pause(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockMicroVMMockRecorder) Pause(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockMicroVM)(nil).Pause), ctx)
}

// Resume mocks base method.
func (m *MockMicroVM) Resume(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockMicroVMMockRecorder) Resume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockMicroVM)(nil).Resume), ctx)
}

// UpdateResources mocks base method.
func (m *MockMicroVM) UpdateResources(ctx context.Context, input firecracker.UpdateResourcesInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResources", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResources indicates an expected call of UpdateResources.
func (mr *MockMicroVMMockRecorder) UpdateResources(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResources", reflect.TypeOf((*MockMicroVM)(nil).UpdateResources), ctx, input)
}

// VSock mocks base method.
func (m *MockMicroVM) VSock() (transport.Transport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VSock")
	ret0, _ := ret[0].(transport.Transport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VSock indicates an expected call of VSock.
func (mr *MockMicroVMMockRecorder) VSock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VSock", reflect.TypeOf((*MockMicroVM)(nil).VSock))
}
