syntax = "proto3";

package nuinfra.auth.v1;

import "google/protobuf/descriptor.proto";

// Actor represents the identity that performed an action on a Resource,
// such as creation, deletion or update. This may be an automation tool or a human user.
//
// The identity is derived from the authentication context.
//
// - For automation: `actor_id` corresponds to the `sub` claim of the
//   automation's identity and `app_name` identifies the automation client.
//
// - For human users: `actor_id` is the user's `sub`, `username` is the
//   individual's login name, and `app_name` identifies the IDP app used
//   during login.
message Actor {
  // A stable unique identifier of the actor, typically the `sub` claim from
  // the oauth token. This ID is consistent across sessions.
  string actor_id = 1;

  // The name of the client application that initiated the action.
  // This may refer to an automation tool or an IDP application.
  optional string app_name = 2;

  // The username of the human actor, if applicable.
  // This field is only populated when the actor is a human.
  optional string username = 3;
}

extend google.protobuf.MethodOptions {
  // Scopes required by the gRPC method. Multiple scopes can be specified by separating them with spaces. For example:
  // `option (required_scopes) = "resource_type:write resource_type:read";`
  optional string required_scopes = 51234;
}

// InsufficientScopes provides further details on unauthorized errors.
message InsufficientScopes {
  // Scopes required for a given operation.
  repeated string required_scopes = 1;
  // Scopes present in the client token.
  repeated string client_scopes = 2;
}
